name: "问题咨询|反馈"
description: "请尽可能详细的描述问题，提供足够的上下文"
labels: ["question"]
body:
  - type: dropdown
    id: version
    attributes:
      label: 版本
      options:
        - "3.x"
        - "2.x"
    validations:
      required: true
  - type: textarea
    id: desired-solution
    attributes:
      label: 问题描述（具体版本号和使用场景，注意：描述不清一句话问题直接关闭）
      description: 详细问题，具体版本号和使用场景，提供相应截图和日志
    validations:
      required: true
